"""add payee to recurring_transactions

Revision ID: 9119de706bcb
Revises: 8cb3aa67ffb6
Create Date: 2026-05-07 13:30:23.591207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9119de706bcb'
down_revision: Union[str, None] = '8cb3aa67ffb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('recurring_transactions', sa.Column('payee', sa.String(length=255), nullable=False, server_default='FIXME'))
    op.execute("UPDATE recurring_transactions SET payee = 'FIXME' WHERE payee = ''")
    # Remove the server default so new inserts must provide a value explicitly
    with op.batch_alter_table('recurring_transactions') as batch_op:
        batch_op.alter_column('payee', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_transactions', 'payee')
    # ### end Alembic commands ###
